package schiffeversenken;

public enum Status {
    START,
    WURFEL_EMPFANGEN,
    WURFEL_GESENDET,
    VERSENKEN_SENDEN,
    BESTAETIGEN_SENDEN,
    VERSENKEN_EMPFANGEN,
    BESTAETIGEN_EMPFANGEN,
    BEENDEN
}
